---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ISLR)
```
```{r}
library(lsr)
```
```{r}
dataCredit <- Credit
head(dataCredit)
```

#SOAL STATISTIKA#
#1
```{r}
mean(dataCredit$Rating)
mean(dataCredit$Cards)
mean(dataCredit$Age)
```


#2
```{r}
modeOf(dataCredit$Gender)
modeOf(dataCredit$Student)
modeOf(dataCredit$Married)
```


#3
```{r}
quantile(x = dataCredit$Education, probs = 0.1)
quantile(x = dataCredit$Education, probs = 0.37)
quantile(x = dataCredit$Education, probs = 0.91)
```


#4
```{r}
quantile(x = dataCredit$Balance, probs =c (0.25, 0.50, 0.75))
boxplot(dataCredit$Balance)
boxplot(dataCredit$Balance, horizontal = TRUE)
```


#5
```{r}
#a
newData <- data.frame(limit = dataCredit$Limit, rating = dataCredit$Rating)
cor(newData)
plot(newData$limit, newData$rating)
#b
newData1 <- data.frame(age = dataCredit$Age, card = dataCredit$Cards)
cor(newData1)
plot(newData1$age, newData1$card)
#c
newData2 <- data.frame(income = dataCredit$Income, education =  dataCredit$Education)
cor(newData2)
plot(newData2$income, newData2$education)
```
